--CREATE TABLE mst_customers (
--  id BIGINT PRIMARY KEY,
--  customer_name VARCHAR(255),
--  customer_gender VARCHAR(10),
--  customer_address VARCHAR(255),
--  customer_phone_number VARCHAR(20),
--  customer_birth_date DATE,
--  id_card_number VARCHAR(20)
--);
--
--CREATE TABLE mst_rooms (
--  id BIGINT PRIMARY KEY AUTO_INCREMENT,
--  room_number BIGINT NOT NULL,
--  room_type VARCHAR(255) NOT NULL
--);
